apiVersion: v1
kind: Service
metadata:
  annotations:
    description: Hot Rod service for clustered applications.
  labels:
    application: datagrid-app
    template: datagrid65-basic
    xpaas: 1.2.0
  name: datagrid-app-hotrod
  namespace: jdg-demo01
spec:
  clusterIP: None
  ports:
  - port: 11333
    protocol: TCP
    targetPort: 11333
  selector:
    deploymentConfig: datagrid-app
  sessionAffinity: None
  type: ClusterIP
